services:
  backend:
    build: ./backend
    env_file: .env
    ports:
      - "5000:5000"
    volumes:
      - ./backend/src:/app

  bot:
    build: ./bot
    env_file: .env
    depends_on:
      - backend

  # frontend:
  #   build: ./frontend
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - ./frontend/src:/app/src

  # nginx:
  #   build: ./nginx
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   depends_on:
  #     - backend
  #     - frontend

  # db:
  #   image: postgres:15
  #   env_file: .env
  #   volumes:
  #     - dbdata:/var/lib/postgresql/data

volumes:
  dbdata: